#pragma once

#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH 1920
#endif // SCREEN_WIDTH

#ifndef SCREEN_HEIGHT
#define SCREEN_HEIGHT 1080
#endif // SCREEN_HEIGHT

#ifndef NUM_GRID_ROWS 
#define NUM_GRID_ROWS 15
#endif // NUM_GRID_ROWS 

#ifndef NUM_GRID_COLUMNS
#define NUM_GRID_COLUMNS 17
#endif // NUM_GRID_COLUMNS

#ifndef WIDTH_INDEX
#define WIDTH_INDEX 0
#endif // WIDTH_INDEX

#ifndef HEIGHT_INDEX
#define HEIGHT_INDEX 1
#endif // HEIGHT_INDEX

#ifndef MARGIN 
#define MARGIN 0.0f
#endif // SCREEN_BORDER_WIDTH

#ifndef SHOW_OVERLAY
#define SHOW_OVERLAY
#endif // SHOW_OVERLAY

#ifndef USE_CONTROLLER
#define USE_CONTROLLER
#endif // USE_CONTROLLER

//#ifndef CONTROLLER_RENDERER
//#define CONTROLLER_RENDERER
//#endif // CONTROLLER_RENDERER

#ifndef XINPUT_ENUM_TIMEOUT_MS
#define XINPUT_ENUM_TIMEOUT_MS 2000
#endif // XINPUT_ENUM_TIMEOUT_MS

#ifndef LEFT_MARGIN_RATIO
#define LEFT_MARGIN_RATIO 0.2f
#endif // LEFT_MARGIN_RATION

#ifndef RIGHT_MARGIN_RATIO
#define RIGHT_MARGIN_RATIO 0.2f
#endif // RIGHT_MARGIN_RATIO