#pragma once

#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH 1920
#endif // SCREEN_WIDTH

#ifndef SCREEN_HEIGHT
#define SCREEN_HEIGHT 1080
#endif // SCREEN_HEIGHT

#ifndef NUM_GRID_ROWS 
#define NUM_GRID_ROWS 15
#endif // NUM_GRID_ROWS 

#ifndef NUM_GRID_COLUMNS
#define NUM_GRID_COLUMNS 17
#endif // NUM_GRID_COLUMNS

#ifndef WIDTH_INDEX
#define WIDTH_INDEX 0
#endif // WIDTH_INDEX

#ifndef HEIGHT_INDEX
#define HEIGHT_INDEX 1
#endif // HEIGHT_INDEX

#ifndef MARGIN 
#define MARGIN 0.0f
#endif // SCREEN_BORDER_WIDTH

//#ifndef SHOW_OVERLAY
//#define SHOW_OVERLAY
//#endif // SHOW_OVERLAY

#ifndef USE_CONTROLLER
#define USE_CONTROLLER
#endif // USE_CONTROLLER

//#ifndef CONTROLLER_RENDERER
//#define CONTROLLER_RENDERER
//#endif // CONTROLLER_RENDERER

#ifndef XINPUT_ENUM_TIMEOUT_MS
#define XINPUT_ENUM_TIMEOUT_MS 2000
#endif // XINPUT_ENUM_TIMEOUT_MS

#ifndef LEFT_MARGIN_RATIO
#define LEFT_MARGIN_RATIO 0.2f
#endif // LEFT_MARGIN_RATIO

#ifndef RIGHT_MARGIN_RATIO
#define RIGHT_MARGIN_RATIO 0.2f
#endif // RIGHT_MARGIN_RATIO

#ifndef PLAYER_WALKING_VELOCITY
#define PLAYER_WALKING_VELOCITY 7.5f	
#endif // PLAYER_WALKING_VELOCITY

#ifndef PLAYER_RUNNING_VELOCITY
#define PLAYER_RUNNING_VELOCITY 12.5f
#endif // PLAYER_RUNNING_VELOCITY

#ifndef NORTH
#define NORTH 0
#endif // NORTH

#ifndef EAST 
#define EAST 1
#endif // EAST

#ifndef SOUTH
#define SOUTH 2
#endif // SOUTH 

#ifndef WEST
#define WEST 3
#endif // WEST

// 5 percent of the screen / second.
#ifndef SCROLLING_VELOCITY
#define SCROLLING_VELOCITY 5
#endif // SCROLLING_VELOCITY

#ifndef SHOW_GRID
#define SHOW_GRID
#endif // SHOW_GRID

#ifndef NUM_HEART_ROWS 
#define NUM_HEART_ROWS 2
#endif // NUM_HEART_ROWS

#ifndef NUM_HEART_COLUMNS
#define NUM_HEART_COLUMNS 10
#endif // NUM_HEART_COLUMN

#ifndef HEART_PANEL_HEIGHT_RATIO
#define HEART_PANEL_HEIGHT_RATIO 0.2f
#endif // HEART_PANEL_RATIO

#ifndef HEART_PANEL_HEIGHT
#define HEART_PANEL_HEIGHT 250.0f
#endif // HEART_PANEL_HEIGHT

#ifndef SECTION_HEADER_FONT_SIZE
#define SECTION_HEADER_FONT_SIZE 36.0f
#endif // SECTION_HEADER_FONT_SIZE

